-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TYPE "public"."admin_role" AS ENUM('admin', 'editor', 'contributor');--> statement-breakpoint
CREATE TYPE "public"."building_type" AS ENUM('admin', 'non-admin');--> statement-breakpoint
CREATE TYPE "public"."edit_proposal_status" AS ENUM('pending', 'approved', 'rejected', 'needs_changes', 'withdrawn');--> statement-breakpoint
CREATE TYPE "public"."event_category" AS ENUM('tradition', 'fair', 'ceremony', 'sports', 'other');--> statement-breakpoint
CREATE TYPE "public"."event_location_anchor" AS ENUM('building', 'dorm', 'custom');--> statement-breakpoint
CREATE TYPE "public"."event_recurrence" AS ENUM('none', 'annual', 'every_1st_sem', 'every_2nd_sem');--> statement-breakpoint
CREATE TABLE "places" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "places_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"category" varchar(24) NOT NULL,
	"lat" double precision,
	"lon" double precision,
	"description" text,
	"hours" text,
	"website_link" text,
	"facebook_link" text,
	"image_url" text,
	"version" integer DEFAULT 1 NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "sponsor_impressions" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"sponsor_id" text NOT NULL,
	"zone" text NOT NULL,
	"event_type" text DEFAULT 'impression' NOT NULL,
	"recorded_at" timestamp with time zone DEFAULT now() NOT NULL,
	"user_agent" text,
	"page_path" text
);
--> statement-breakpoint
CREATE TABLE "jeepney_routes" (
	"id" varchar(64) PRIMARY KEY NOT NULL,
	"name" varchar(120) NOT NULL,
	"description" text NOT NULL,
	"direction_note" text,
	"color" varchar(16) NOT NULL,
	"fare_regular" double precision NOT NULL,
	"fare_discounted" double precision NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "jeepney_stops" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "jeepney_stops_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"route_id" varchar(64) NOT NULL,
	"name" varchar(160) NOT NULL,
	"description" text NOT NULL,
	"lat" double precision NOT NULL,
	"lon" double precision NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "presence" (
	"sid" varchar(64) PRIMARY KEY NOT NULL,
	"last_seen_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "dorms" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "dorms_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"dorm_name" text NOT NULL,
	"short_name" varchar(48),
	"lat" double precision,
	"lon" double precision,
	"gender" text,
	"capacity" integer,
	"managing_office" text,
	"contact_email" text,
	"amenities" text[],
	"osm_link" text,
	"description" text,
	"is_up_managed" boolean DEFAULT true,
	"price_range" text,
	"contact_phone" varchar(20)[],
	"facebook_link" text,
	"version" integer DEFAULT 1 NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"image_url" text
);
--> statement-breakpoint
CREATE TABLE "rooms" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rooms_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"room_code" text NOT NULL,
	"directions" text,
	"building_id" integer,
	"college_id" integer,
	"division_id" integer,
	"version" integer DEFAULT 1 NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"image_url" text,
	"category" varchar(24),
	"full_name" text
);
--> statement-breakpoint
CREATE TABLE "classes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "classes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"course_code" varchar(16),
	"section" varchar(16),
	"type" varchar(12),
	"schedule" text[],
	"room_id" integer,
	"course_title" text,
	"term_id" integer,
	"version" integer DEFAULT 1 NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"acad_group" varchar(8),
	"acad_org" varchar(16)
);
--> statement-breakpoint
CREATE TABLE "organizations" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "organizations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"category" varchar(24) NOT NULL,
	"building_id" integer,
	"room_id" integer,
	"lat" double precision,
	"lon" double precision,
	"description" text,
	"website_link" text,
	"facebook_link" text,
	"email" text,
	"image_url" text,
	"version" integer DEFAULT 1 NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"bio" text,
	"org_type" varchar(32),
	"established_year" varchar(8),
	"member_count" varchar(16)
);
--> statement-breakpoint
CREATE TABLE "colleges" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "colleges_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"college_name" varchar(100) NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"website_link" text
);
--> statement-breakpoint
CREATE TABLE "divisions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "divisions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"division_name" varchar(100) NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"college_id" integer,
	"website_link" text
);
--> statement-breakpoint
CREATE TABLE "event_locations" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "event_locations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"event_id" integer NOT NULL,
	"anchor_type" "event_location_anchor" NOT NULL,
	"building_id" integer,
	"dorm_id" integer,
	"label" text NOT NULL,
	"lat" double precision,
	"lon" double precision,
	"highlight_priority" integer DEFAULT 0 NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"is_primary" boolean DEFAULT false NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "schema_migrations" (
	"filename" text PRIMARY KEY NOT NULL,
	"applied_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "events" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "events_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"slug" varchar(120) NOT NULL,
	"title" varchar(160) NOT NULL,
	"description" text,
	"category" "event_category" DEFAULT 'other' NOT NULL,
	"starts_at" timestamp NOT NULL,
	"ends_at" timestamp NOT NULL,
	"timezone" varchar(64) DEFAULT 'Asia/Manila' NOT NULL,
	"recurrence" "event_recurrence" DEFAULT 'none' NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"source_url" text,
	"priority" integer DEFAULT 0 NOT NULL,
	"include_in_seo" boolean DEFAULT false NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"image_url" text
);
--> statement-breakpoint
CREATE TABLE "update" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "update_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"table_name" varchar(20),
	"sync_key" uuid DEFAULT gen_random_uuid()
);
--> statement-breakpoint
CREATE TABLE "edit_proposals" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "edit_proposals_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"entity_type" varchar(32) NOT NULL,
	"entity_id" integer NOT NULL,
	"status" "edit_proposal_status" DEFAULT 'pending' NOT NULL,
	"proposed_patch" jsonb NOT NULL,
	"base_version" integer NOT NULL,
	"submitter_name" varchar(100) NOT NULL,
	"submitter_user_id" integer,
	"admin_note" text,
	"reviewed_by" varchar(100),
	"reviewed_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"submitter_note" text
);
--> statement-breakpoint
CREATE TABLE "admin_users" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "admin_users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"username" varchar(64) NOT NULL,
	"display_name" varchar(100),
	"password_hash" text NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"role" "admin_role" DEFAULT 'editor' NOT NULL,
	"supabase_user_id" uuid,
	"email" text,
	"deleted_at" timestamp,
	"avatar_url" text,
	"profile_url" text,
	"show_in_credits" boolean DEFAULT true NOT NULL,
	"legacy_credit" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
CREATE TABLE "buildings" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "buildings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"building_name" varchar(100) NOT NULL,
	"lon" double precision NOT NULL,
	"lat" double precision NOT NULL,
	"directions" text NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"type" "building_type" DEFAULT 'non-admin' NOT NULL,
	"image_url" text,
	"cr_facilities" text[],
	"street_view_pano_id" varchar(128),
	"street_view_captured" varchar(16),
	"street_view_distance_m" integer,
	"street_view_checked_at" timestamp
);
--> statement-breakpoint
CREATE TABLE "aliases" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "aliases_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"alias" text NOT NULL,
	"normalized_alias" text NOT NULL,
	"target_type" varchar(16) NOT NULL,
	"target_id" integer NOT NULL,
	"source" varchar(32),
	"confidence" varchar(16) DEFAULT 'unverified' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "final_exams" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "final_exams_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"term_id" integer NOT NULL,
	"course_code" varchar(16) NOT NULL,
	"section" varchar(16),
	"course_title" text,
	"room_id" integer,
	"exam_date" date NOT NULL,
	"starts_at" time NOT NULL,
	"ends_at" time NOT NULL,
	"source" varchar(64) NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "planner_plans" (
	"user_id" integer PRIMARY KEY NOT NULL,
	"data" jsonb NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "contributions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "contributions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer,
	"submitter_name" varchar(100),
	"entity_type" varchar(32) NOT NULL,
	"entity_id" integer NOT NULL,
	"entity_label" text NOT NULL,
	"source" varchar(32) NOT NULL,
	"proposal_id" integer,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "flora_species" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "flora_species_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"scientific_name" text NOT NULL,
	"family" text,
	"common_names" text[],
	"description" text,
	"image_url" text,
	"conservation_status" varchar(32),
	"is_native" boolean,
	"version" integer DEFAULT 1 NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "flora_species_scientific_name_unique" UNIQUE("scientific_name")
);
--> statement-breakpoint
CREATE TABLE "flora_specimens" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "flora_specimens_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"species_id" integer NOT NULL,
	"lat" double precision NOT NULL,
	"lon" double precision NOT NULL,
	"tag_number" varchar(32),
	"planted_year" integer,
	"notes" text,
	"is_notable" boolean DEFAULT false NOT NULL,
	"source" varchar(32) DEFAULT 'manual' NOT NULL,
	"source_ref" text,
	"source_licence" varchar(64),
	"version" integer DEFAULT 1 NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "terms" (
	"id" integer PRIMARY KEY NOT NULL,
	"label" text NOT NULL,
	"school_year" varchar(16),
	"semester" varchar(12),
	"starts_on" timestamp,
	"ends_on" timestamp,
	"is_default" boolean DEFAULT false NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"classes_imported_at" timestamp
);
--> statement-breakpoint
CREATE TABLE "announcements" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "announcements_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" text NOT NULL,
	"body" text NOT NULL,
	"severity" varchar(16) DEFAULT 'info' NOT NULL,
	"starts_on" timestamp DEFAULT now() NOT NULL,
	"ends_on" timestamp,
	"link_url" text,
	"author" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "feedback" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "feedback_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"message" text NOT NULL,
	"contact" text,
	"screen" text,
	"app_version" text,
	"was_online" boolean,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "room_positions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "room_positions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"floor" integer NOT NULL,
	"pos_x" numeric NOT NULL,
	"pos_y" numeric NOT NULL,
	"updated_at" timestamp NOT NULL,
	"room_id" integer NOT NULL,
	"source" varchar(16) DEFAULT 'manual' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "event_route_stops" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "event_route_stops_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"route_id" integer NOT NULL,
	"event_location_id" integer,
	"label" text NOT NULL,
	"lat" double precision,
	"lon" double precision,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "event_routes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "event_routes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"event_id" integer NOT NULL,
	"name" varchar(120) NOT NULL,
	"description" text,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "editor_history" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "editor_history_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"entity_type" varchar(32) NOT NULL,
	"entity_id" integer NOT NULL,
	"action" varchar(32) NOT NULL,
	"before_snapshot" jsonb,
	"after_snapshot" jsonb,
	"version_before" integer,
	"version_after" integer,
	"edited_by" varchar(100) DEFAULT 'admin' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"summary" text
);
--> statement-breakpoint
ALTER TABLE "jeepney_stops" ADD CONSTRAINT "jeepney_stops_route_id_jeepney_routes_id_fk" FOREIGN KEY ("route_id") REFERENCES "public"."jeepney_routes"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rooms" ADD CONSTRAINT "room_building" FOREIGN KEY ("building_id") REFERENCES "public"."buildings"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rooms" ADD CONSTRAINT "room_college" FOREIGN KEY ("college_id") REFERENCES "public"."colleges"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rooms" ADD CONSTRAINT "room_division" FOREIGN KEY ("division_id") REFERENCES "public"."divisions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "classes" ADD CONSTRAINT "class_room" FOREIGN KEY ("room_id") REFERENCES "public"."rooms"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "divisions" ADD CONSTRAINT "division_college" FOREIGN KEY ("college_id") REFERENCES "public"."colleges"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "event_locations" ADD CONSTRAINT "event_location_building" FOREIGN KEY ("building_id") REFERENCES "public"."buildings"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "event_locations" ADD CONSTRAINT "event_location_dorm" FOREIGN KEY ("dorm_id") REFERENCES "public"."dorms"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "event_locations" ADD CONSTRAINT "event_location_event" FOREIGN KEY ("event_id") REFERENCES "public"."events"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "edit_proposals" ADD CONSTRAINT "edit_proposals_submitter_user_id_admin_users_id_fk" FOREIGN KEY ("submitter_user_id") REFERENCES "public"."admin_users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "final_exams" ADD CONSTRAINT "final_exam_room" FOREIGN KEY ("room_id") REFERENCES "public"."rooms"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "final_exams" ADD CONSTRAINT "final_exam_term" FOREIGN KEY ("term_id") REFERENCES "public"."terms"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "planner_plans" ADD CONSTRAINT "planner_plans_user_id_admin_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."admin_users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "contributions" ADD CONSTRAINT "contributions_proposal_id_edit_proposals_id_fk" FOREIGN KEY ("proposal_id") REFERENCES "public"."edit_proposals"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "contributions" ADD CONSTRAINT "contributions_user_id_admin_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."admin_users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "flora_specimens" ADD CONSTRAINT "flora_specimens_species_id_fkey" FOREIGN KEY ("species_id") REFERENCES "public"."flora_species"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "room_positions" ADD CONSTRAINT "room_position_id" FOREIGN KEY ("room_id") REFERENCES "public"."rooms"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "event_route_stops" ADD CONSTRAINT "event_route_stop_location" FOREIGN KEY ("event_location_id") REFERENCES "public"."event_locations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "event_route_stops" ADD CONSTRAINT "event_route_stop_route" FOREIGN KEY ("route_id") REFERENCES "public"."event_routes"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "event_routes" ADD CONSTRAINT "event_route_event" FOREIGN KEY ("event_id") REFERENCES "public"."events"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_sponsor_imp_sponsor_date" ON "sponsor_impressions" USING btree ("sponsor_id" text_ops,"recorded_at" text_ops);--> statement-breakpoint
CREATE INDEX "idx_sponsor_imp_zone_date" ON "sponsor_impressions" USING btree ("zone" timestamptz_ops,"recorded_at" timestamptz_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "jeepney_stops_route_sort_order" ON "jeepney_stops" USING btree ("route_id" int4_ops,"sort_order" int4_ops);--> statement-breakpoint
CREATE INDEX "idx_presence_last_seen" ON "presence" USING btree ("last_seen_at" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "classes_term_course_section_id_idx" ON "classes" USING btree (term_id int4_ops,COALESCE(course_code, ''::character varying) int4_ops,COALESCE(section, ''::character varying) int4_ops,id int4_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "events_slug_unique" ON "events" USING btree ("slug" text_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "update_table_name_key" ON "update" USING btree ("table_name" text_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "admin_users_username_unique" ON "admin_users" USING btree ("username" text_ops);--> statement-breakpoint
CREATE INDEX "buildings_street_view_pano_idx" ON "buildings" USING btree ("id" int4_ops) WHERE (street_view_pano_id IS NOT NULL);--> statement-breakpoint
CREATE UNIQUE INDEX "aliases_normalized_target" ON "aliases" USING btree ("normalized_alias" text_ops,"target_type" int4_ops,"target_id" text_ops);--> statement-breakpoint
CREATE INDEX "flora_specimens_notable_idx" ON "flora_specimens" USING btree ("is_notable" bool_ops);--> statement-breakpoint
CREATE INDEX "flora_specimens_species_idx" ON "flora_specimens" USING btree ("species_id" int4_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "terms_single_default" ON "terms" USING btree ("is_default" bool_ops) WHERE is_default;--> statement-breakpoint
CREATE INDEX "feedback_created_at_idx" ON "feedback" USING btree ("created_at" timestamp_ops);
*/