-- In-app announcements (#777): editorial notices with a publish window.
CREATE TABLE IF NOT EXISTS "announcements" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "announcements_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" text NOT NULL,
	"body" text NOT NULL,
	"severity" varchar(16) DEFAULT 'info' NOT NULL,
	"starts_on" timestamp DEFAULT now() NOT NULL,
	"ends_on" timestamp,
	"link_url" text,
	"author" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);

-- Client-side PGlite sync needs a registry row per cached table.
INSERT INTO "update" ("table_name")
VALUES ('announcements')
ON CONFLICT ("table_name") DO UPDATE
SET "sync_key" = gen_random_uuid();
