/**
 * Single source of truth for the `src/campus.config.ts` a fork pastes over
 * its checkout. Consumed by the /fork wizard island.
 *
 * NOTE: scripts/fork-init.ts (in-flight PR `feat/fork-config-surface`) should
 * consume this same module once both merge, so the CLI prompts and the wizard
 * never generate divergent configs.
 */
import { slugifySegment } from "../site";

export type ForkConfig = {
  /** Full campus name, e.g. "University of the Philippines Diliman". */
  name: string;
  /** URL-safe short name, e.g. "upd". Drives the Vercel project name. */
  slug: string;
  /** Where the fork will be hosted, e.g. "https://upd-room-tba.vercel.app". */
  siteUrl: string;
  /** Campus center as [lng, lat]. */
  center: [number, number];
  /** Map max bounds: [[west, south], [east, north]] in lng/lat. */
  bounds: [[number, number], [number, number]];
  defaultZoom: number;
  transitOverlay: boolean;
  /** Label for the transit overlay toggle, e.g. "Jeepney routes". */
  transitLabel: string;
  terrain: boolean;
};

export function campusSlug(name: string): string {
  return slugifySegment(name);
}

const UPSTREAM_REPO_URL = "https://github.com/uplbtools/room-tba";

/** Vercel "Deploy" clone URL prefilled with the fork's env prompts. */
export function vercelDeployUrl(slug: string): string {
  const params = new URLSearchParams({
    "repository-url": UPSTREAM_REPO_URL,
    env: "DATABASE_URL,ADMIN_PASSWORD,ADMIN_SESSION_SECRET,ISR_BYPASS_TOKEN",
    envDescription: "See .env.example",
    "project-name": `${slug}-room-tba`,
  });
  return `https://vercel.com/new/clone?${params.toString()}`;
}

/** ~0.1 m precision; map clicks otherwise emit 15+ decimals. */
const coord = (n: number) => Number(n.toFixed(6));
const zoomValue = (n: number) => Number(n.toFixed(2));

/**
 * Render the full campus.config.ts contents. Mirrors the current shape of
 * `src/campus.config.ts` (campusSite / campusMap / campusCommunity); community
 * links carry over upstream values with a marker comment for the fork to edit.
 */
export function generateCampusConfig(config: ForkConfig): string {
  const lng = coord(config.center[0]);
  const lat = coord(config.center[1]);
  const west = coord(config.bounds[0][0]);
  const south = coord(config.bounds[0][1]);
  const east = coord(config.bounds[1][0]);
  const north = coord(config.bounds[1][1]);
  return `/**
 * Single source of truth for campus-specific config.
 *
 * Generated by the Room TBA fork wizard (/fork) for ${config.name}.
 * Run \`bun run fork:check\` after editing to catch stray upstream strings.
 *
 * Values are plain literals so astro.config.mjs can import this module at
 * config-eval time (no process.env reads at module top level).
 */

export const campusSite = {
  url: "${config.siteUrl}",
  name: "Room TBA",
  title: "Room TBA | Find Rooms and Buildings at ${config.name}",
  description:
    "Room TBA helps ${config.name} students find rooms, buildings, and classes across campus.",
} as const;

export const campusMap: {
  maxBounds: [[number, number], [number, number]];
  defaultCamera: {
    center: [number, number];
    zoom: number;
    pitch: number;
    bearing: number;
  };
} = {
  /** [lng, lat] — west/south corner, then east/north corner. */
  maxBounds: [
    [${west}, ${south}],
    [${east}, ${north}],
  ],
  /** Default camera: center [lng, lat], zoom, pitch (0 = top-down, 60 = tilted 3D), bearing. */
  defaultCamera: {
    center: [${lng}, ${lat}],
    zoom: ${zoomValue(config.defaultZoom)},
    pitch: 0,
    bearing: 0,
  },
};

// TODO(fork): replace with your campus community links, or delete unused keys.
export const campusCommunity = {
  orgUrl: "${UPSTREAM_REPO_URL}",
  githubUrl: "${UPSTREAM_REPO_URL}",
  discordUrl: "${UPSTREAM_REPO_URL}",
  osaOrganizationsUrl: "${UPSTREAM_REPO_URL}",
  messengerContributeTarget: "${UPSTREAM_REPO_URL}",
  messengerMaintainTarget: "${UPSTREAM_REPO_URL}",
  messengerShortContributeUrl: "${UPSTREAM_REPO_URL}",
  messengerShortMaintainUrl: "${UPSTREAM_REPO_URL}",
} as const;

/**
 * Fork options recorded by the wizard — wired into campus.config once the
 * in-flight \`feat/fork-config-surface\` PR lands:
 * - transit overlay: ${config.transitOverlay ? `enabled, labeled "${config.transitLabel}"` : "disabled"}
 * - terrain: ${config.terrain ? "enabled" : "disabled"}
 */
`;
}
